const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));let deliveryFilter='all',peopleFilter='all';
const DATA=loadRealData();
function safeParse(v){try{return JSON.parse(v)}catch(e){return null}}
function pick(o,ks,d=''){for(const k of ks){if(o&&o[k]!=null&&o[k]!=='')return o[k]}return d}
function txt(v){return v==null?'':String(v)}
function getArrays(){const keys=['worktimeData','worktime_v2_data','sls_worktime_data','projects','employees','users','tasks','scheduleData','project_members','time_logs'];const box={projects:[],people:[],tasks:[]};keys.forEach(k=>{const j=safeParse(localStorage.getItem(k));if(!j)return;if(Array.isArray(j))classify(k,j,box);else if(typeof j==='object')Object.keys(j).forEach(x=>Array.isArray(j[x])&&classify(x,j[x],box))});return box}
function classify(name,arr,box){const n=name.toLowerCase();if(n.includes('employee')||n.includes('user')||n.includes('people'))box.people.push(...arr);else if(n.includes('task')||n.includes('member')||n.includes('log')||n.includes('schedule'))box.tasks.push(...arr);else if(n.includes('project'))box.projects.push(...arr)}
function fmtDate(v){if(!v)return '未填';const d=new Date(v);return isNaN(d)?String(v):(d.getMonth()+1)+'月'+d.getDate()+'日'}
function leftDays(v){const d=new Date(v);return isNaN(d)?9999:Math.ceil((d-new Date())/86400000)}
function risk(v,due){const s=txt(v).toLowerCase();if(s.includes('高')||s.includes('red')||s.includes('high')||s.includes('逾期'))return 'high';if(s.includes('中')||s.includes('mid')||s.includes('卡')||s.includes('黄'))return 'mid';if(due<=3)return 'high';if(due<=10)return 'mid';return 'normal'}
function normalProject(o){const d=pick(o,['delivery','deliveryDate','delivery_date','deadline','dueDate','contract_delivery_date','endDate','finishDate','plannedEnd'],'');const due=leftDays(d);const name=txt(pick(o,['name','title','project_name','projectName','项目名称'],''));return {id:txt(pick(o,['id','project_id','uuid','code'],name)),name,kind:txt(pick(o,['kind','type','project_type','status_type'],'')).includes('预')?'pre':'contract',delivery:d,deliveryLabel:fmtDate(d),deliverable:txt(pick(o,['deliverable','output','scope','交付物'],'交付节点')),preEnd:fmtDate(pick(o,['preEnd','pre_end','plannedEnd'],d)),access:fmtDate(pick(o,['access','accessDate','site_start','entry_date','预计接铺'],'')),opening:fmtDate(pick(o,['opening','openingDate','open_date','预计开业'],'')),stage:txt(pick(o,['stage','status','phase','current_stage','当前阶段'],'未填')),risk:risk(pick(o,['risk','riskLevel','risk_level','warning'],''),due),ownerPlan:txt(pick(o,['ownerPlan','plan_owner','designer','scheme_designer','方案负责人','owner'],'')),ownerTech:txt(pick(o,['ownerTech','tech_owner','deepener','drawing_designer','深化负责人'],'')),owner:txt(pick(o,['owner','manager','负责人'],'')),issue:txt(pick(o,['issue','risk_reason','remark','note','备注'],'暂无风险说明'))}}
function normalPerson(o){const name=txt(pick(o,['name','nickname','display_name','employee_name','user_name','姓名'],''));return {id:txt(pick(o,['id','user_id','employee_id','uuid'],name)),name,role:txt(pick(o,['role','position','job','岗位'],'未标注')),cap:Number(pick(o,['cap','capacity','max_projects','负载上限'],2))||2,items:[]}}
function normalTask(o){return {project:txt(pick(o,['project','project_name','projectName','项目名称','title'],'')),person:txt(pick(o,['person','employee','employee_name','user','user_name','designer','owner','assignee','负责人','姓名'],'')),personId:txt(pick(o,['employee_id','user_id','assignee_id'],'')),stage:txt(pick(o,['stage','phase','task_class','category','阶段','task','task_name','content','工作内容'],'')),date:pick(o,['date','work_date','start','end','deadline','due_date','created_at'],''),risk:pick(o,['risk','riskLevel','status'],'')}}
function loadRealData(){const raw=getArrays();let projects=raw.projects.map(normalProject).filter(p=>p.name);let people=raw.people.map(normalPerson).filter(p=>p.name);const tasks=raw.tasks.map(normalTask).filter(t=>t.project||t.person);if(!projects.length){const m=new Map();tasks.forEach(t=>t.project&&!m.has(t.project)&&m.set(t.project,normalProject({name:t.project,stage:t.stage,delivery:t.date,owner:t.person})));projects=[...m.values()]}
if(!people.length){const m=new Map();projects.forEach(p=>[p.ownerPlan,p.ownerTech,p.owner].forEach(n=>n&&!m.has(n)&&m.set(n,{id:n,name:n,role:'未标注',cap:2,items:[]})));tasks.forEach(t=>t.person&&!m.has(t.person)&&m.set(t.person,{id:t.person,name:t.person,role:'未标注',cap:2,items:[]}));people=[...m.values()]}
people.forEach(p=>{p.items=tasks.filter(t=>t.person===p.name||t.personId===p.id).map(t=>[t.project||'未命名项目',t.stage||'进行中',fmtDate(t.date),risk(t.risk,leftDays(t.date))])});return {projects,people,tasks}}
function riskClass(r){return r==='high'?'red':r==='mid'?'gold':'green'}function riskText(r){return r==='high'?'高风险':r==='mid'?'卡点':'正常'}function kindText(k){return k==='pre'?'预排项目':'合同项目'}function progress(d){const l=leftDays(d);return l===9999?15:Math.max(12,Math.min(96,100-l*3))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1600)}
function openSheet(h){$('#sheetContent').innerHTML=h;$('#mask').classList.add('show');$('#sheet').classList.add('show')}function closeSheet(){$('#mask').classList.remove('show');$('#sheet').classList.remove('show')}
function empty(m){return `<div class="note">${m}</div>`}
function cardProject(p,mode=''){const rc=riskClass(p.risk);return `<article class="card ${rc}" onclick="openProject('${p.id}')"><h3>${p.name}</h3><p>${p.kind==='contract'?'合同交付':'预排结束'}：${p.deliveryLabel} ${p.deliverable}\n预计接铺：${p.access}｜预计开业：${p.opening}\n当前阶段：${p.stage}</p><span class="tag risk">${riskText(p.risk)}</span><span class="tag blue">${kindText(p.kind)}</span><div class="tl"><span>进度</span><span>${p.deliveryLabel}</span></div><div class="track"><div class="fill ${rc}" style="width:${progress(p.delivery)}%"></div></div>${mode==='today'?`<div class="actions"><button class="btn ${p.risk==='high'?'red':'blue'}" onclick="event.stopPropagation();openProject('${p.id}')">打开交付卡</button><button class="btn" onclick="event.stopPropagation();riskAdvice('${p.id}')">处理建议</button></div>`:''}</article>`}
function personCard(p,compact=false){const c=p.items.length,over=c>p.cap,cls=over?'red':'green';return `<article class="card ${cls}" onclick="openPerson('${p.id||p.name}')"><h3>${p.name}｜${p.role}</h3><p>${over?'超过建议上限，新增任务需拆分或换人':'负载正常，可作为备选人选'}\n推荐依据展示为规则化信息，不做黑盒 AI 判断。</p><span class="tag risk">${over?'过载 '+c+'项':'正常 '+c+'项'}</span>${p.items.length?p.items.map(i=>`<div class="line"><b>${i[0]}</b><span>${i[1]}</span><span>${i[2]}</span></div>`).join(''):'<p style="margin-top:10px">暂无进行中任务记录</p>'}${compact?`<div class="actions one"><button class="btn" onclick="event.stopPropagation();openPerson('${p.id||p.name}')">查看人员负载</button></div>`:''}</article>`}
function renderToday(){const ps=DATA.projects,pe=DATA.people;$('#kpiDue').textContent=ps.filter(p=>leftDays(p.delivery)<=20).length;$('#kpiPre').textContent=ps.filter(p=>p.kind==='pre').length;$('#kpiOver').textContent=pe.filter(x=>x.items.length>x.cap).length;let h='';if(ps.length)h+=ps.slice().sort((a,b)=>leftDays(a.delivery)-leftDays(b.delivery)).slice(0,2).map(p=>cardProject(p,'today')).join('');if(pe.length)h+=pe.slice().sort((a,b)=>b.items.length-a.items.length).slice(0,1).map(p=>personCard(p,true)).join('');$('#todayList').innerHTML=h||empty('没有读取到历史项目或人员数据。已移除测试姓名，不再显示张三李四等虚构数据。')}
function renderDelivery(){const q=($('#projectSearch').value||'').trim().toLowerCase();let a=DATA.projects.filter(p=>!q||[p.name,p.stage,p.ownerPlan,p.ownerTech,p.owner].join(' ').toLowerCase().includes(q));if(deliveryFilter==='contract')a=a.filter(p=>p.kind==='contract');if(deliveryFilter==='pre')a=a.filter(p=>p.kind==='pre');if(deliveryFilter==='risk')a=a.filter(p=>p.risk!=='normal');a.sort((x,y)=>leftDays(x.delivery)-leftDays(y.delivery));$('#deliveryList').innerHTML=a.length?a.map(p=>cardProject(p)).join(''):empty('没有匹配项目，或当前浏览器本地没有历史项目数据。')}
function renderPeople(){let a=DATA.people.slice();if(peopleFilter==='方案')a=a.filter(p=>p.role.includes('方案'));if(peopleFilter==='深化')a=a.filter(p=>p.role.includes('深化'));if(peopleFilter==='over')a=a.filter(p=>p.items.length>p.cap);$('#peopleList').innerHTML=a.length?a.map(p=>personCard(p)).join(''):empty('没有读取到人员数据。已取消测试人员占位，避免误导排期。')}
function renderMore(){$('#moreList').innerHTML=[['绩效参考导出','只导出参与事实，不计算提成金额','export'],['项目风险处理建议','生成可复制给老板/总监的处理口径','risk'],['AI审图测试台','手机只保留入口，建议电脑端处理','review'],['系统自检','检查移动端是否读取到数据','check']].map(m=>`<div class="more-row" onclick="moreAction('${m[2]}')"><div><b>${m[0]}</b><small>${m[1]}</small></div><span>›</span></div>`).join('')+'<div class="note">边界：工时管家负责项目进度、人员负载、工时成本、风险预警；正式绩效、离职结算、接档金额、尾款绩效全部放飞书处理。</div>'}
function openProject(id){const p=DATA.projects.find(x=>x.id==id);if(!p)return;const rc=riskClass(p.risk);openSheet(`<h2>${p.name}</h2><p class="sub">老板问“什么时候结束”，这里一屏回答。</p><div class="big-date"><b>${p.deliveryLabel}</b><span>${p.kind==='contract'?'合同约定':'预排节点'}：${p.deliverable}</span></div><article class="card ${rc}"><h3>当前阶段：${p.stage}</h3><p>${p.issue}\n方案负责人：${p.ownerPlan||p.owner||'未填'}｜深化负责人：${p.ownerTech||'未填'}\n说明：施工阶段只作为进度状态，不作为绩效发放条件。</p></article><div class="actions"><button class="btn blue" onclick="copyBrief('${p.id}')">复制老板口径</button><button class="btn" onclick="riskAdvice('${p.id}')">生成处理建议</button></div>`)}
function openPerson(id){const p=DATA.people.find(x=>x.id==id||x.name==id);if(!p)return;const c=p.items.length,over=c>p.cap;openSheet(`<h2>${p.name} / ${p.role}</h2><p class="sub">清楚看到他为什么能接或不能再加任务。</p><article class="card ${over?'red':'green'}"><h3>当前 ${c} 个进行中项目</h3><p>${over?'超过建议上限，新增任务需拆分或换人':'负载正常，可以作为备选人选'}\n建议上限：同时 ${p.cap} 个进行中项目。</p></article>${p.items.length?p.items.map(i=>`<article class="card ${riskClass(i[3])}"><h3>${i[0]}</h3><p>阶段：${i[1]}\n交付/释放：${i[2]}</p></article>`).join(''):empty('暂无进行中任务记录')}<div class="actions"><button class="btn" onclick="staffingAdvice('${p.id||p.name}')">生成人员安排建议</button><button class="btn blue" onclick="toast('已标记为需拆分任务')">标记拆分</button></div>`)}
function copyBrief(id){const p=DATA.projects.find(x=>x.id==id);if(!p)return;const m=`${p.name}目前${p.kind==='contract'?'合同交付':'预排结束'}节点是${p.deliveryLabel}，内容为${p.deliverable}，预计${p.access}接铺，${p.opening}开业。当前阶段是${p.stage}，${p.issue}。`;navigator.clipboard&&navigator.clipboard.writeText(m);toast('已复制老板口径')}
function riskAdvice(id){const p=DATA.projects.find(x=>x.id==id)||DATA.projects.find(x=>x.risk!=='normal');if(!p){toast('暂无项目数据');return}const m=`项目：${p.name}\n风险：${p.issue}\n建议：\n1. 今天先确认${p.ownerPlan||p.owner||'负责人'}与${p.ownerTech||'深化负责人'}的当前卡点；\n2. 如果${p.deliveryLabel}前无法完成${p.deliverable}，立即拆分任务或调整负责人；\n3. 对外只同步交付影响，不讨论内部绩效或责任分配；\n4. 施工阶段只作为进度状态，不作为绩效发放节点。`;openSheet(`<h2>处理建议</h2><p class="sub">可复制给老板或总监。</p><textarea class="export" id="adviceText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('adviceText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function staffingAdvice(id){const p=DATA.people.find(x=>x.id==id||x.name==id);if(!p)return;const c=p.items.length,over=c>p.cap,m=`人员：${p.name}｜${p.role}\n当前负载：${c}/${p.cap}\n判断：${over?'不建议新增完整项目，可拆分收尾任务或换人':'可作为备选，但仍需看交付时间冲突'}\n依据：${p.items.map(i=>i[0]+'-'+i[1]+'-'+i[2]).join('；')||'暂无任务记录'}\n注意：这是规则化负载判断，不是黑盒 AI 自动派工。`;openSheet(`<h2>人员安排建议</h2><p class="sub">依据角色、负载和项目占用生成。</p><textarea class="export" id="staffText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('staffText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function performanceCSV(){const h=['员工姓名','项目名称','项目角色','参与起始日期','参与结束日期','累计工时','项目总工时','工时占比','当前项目状态','是否接档','接档员工','接档日期','备注'],r=[];DATA.people.forEach(p=>p.items.forEach(i=>r.push([p.name,i[0],p.role,'','','','','',i[1],'','','','仅作绩效参考，不自动计算提成金额'])));return [h,...r].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n')}
function openExport(){const c=performanceCSV();openSheet(`<h2>绩效参考导出</h2><p class="sub">只导出参与事实，给飞书绩效表作参考；不计算 50% / 40% / 10% 提成。</p><div class="note">工时占比只能作为参考，不能自动等于绩效分配比例。</div><textarea class="export" id="csvText">${c}</textarea><div class="actions"><button class="btn blue" onclick="copyText('csvText')">复制 CSV</button><button class="btn" onclick="downloadCSV()">下载 CSV</button></div>`)}
function copyText(id){const e=document.getElementById(id);e.select();document.execCommand('copy');toast('已复制')}function downloadCSV(){const b=new Blob(['\ufeff'+performanceCSV()],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='绩效参考导出.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已生成 CSV')}
function moreAction(a){if(a==='export')openExport();else if(a==='risk')riskAdvice(DATA.projects.find(p=>p.risk!=='normal')&&DATA.projects.find(p=>p.risk!=='normal').id);else if(a==='check')toast(`读取到 ${DATA.projects.length} 个项目、${DATA.people.length} 个人员`);else toast('该功能保留为电脑端入口，手机端不展开')}
function switchPage(n){$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+n).classList.add('active');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===n));$('#title').textContent={today:'今日',delivery:'交付时间',people:'人员负载',more:'更多'}[n]}
$$('.tab').forEach(t=>t.onclick=()=>switchPage(t.dataset.page));$('#mask').onclick=closeSheet;$('#projectSearch').oninput=renderDelivery;$$('#deliveryFilters .pill').forEach(b=>b.onclick=()=>{$$('#deliveryFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');deliveryFilter=b.dataset.filter;renderDelivery()});$$('#peopleFilters .pill').forEach(b=>b.onclick=()=>{$$('#peopleFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');peopleFilter=b.dataset.role;renderPeople()});function tick(){const d=new Date();$('#clock').textContent=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}tick();setInterval(tick,30000);renderToday();renderDelivery();renderPeople();renderMore();