const projects=[{id:'p1',name:'植物园项目',kind:'contract',delivery:'2026-05-18',deliveryLabel:'5月18日',deliverable:'施工图 CAD+PDF',preEnd:'5月16日',access:'5月22日',opening:'6月30日',stage:'方案未锁定',risk:'high',ownerPlan:'王五',ownerTech:'张三',issue:'方案未最终锁定，施工图时间被压缩'},{id:'p2',name:'ONIONIO 常州店',kind:'pre',delivery:'2026-05-24',deliveryLabel:'5月24日',deliverable:'预排结束',preEnd:'5月24日',access:'5月6日',opening:'6月18日',stage:'深化中',risk:'normal',ownerPlan:'赵六',ownerTech:'李四',issue:'节点正常，需确认施工图输出时间'},{id:'p3',name:'烘焙店项目',kind:'contract',delivery:'2026-05-28',deliveryLabel:'5月28日',deliverable:'方案+施工图',preEnd:'5月26日',access:'6月1日',opening:'7月5日',stage:'材料节点复核',risk:'mid',ownerPlan:'王五',ownerTech:'张三',issue:'风炉高温区域材料方案未定'},{id:'p4',name:'快闪店项目',kind:'pre',delivery:'2026-05-10',deliveryLabel:'5月10日',deliverable:'深化收尾',preEnd:'5月10日',access:'5月12日',opening:'5月30日',stage:'深化收尾',risk:'mid',ownerPlan:'赵六',ownerTech:'张三',issue:'深化负责人排期冲突，建议拆分收尾任务'},{id:'p5',name:'餐饮A 项目',kind:'contract',delivery:'2026-05-21',deliveryLabel:'5月21日',deliverable:'概念方案',preEnd:'5月20日',access:'6月10日',opening:'7月20日',stage:'概念方案',risk:'normal',ownerPlan:'王五',ownerTech:'李四',issue:'方案推进正常'}];
const people=[{name:'张三',role:'深化设计',cap:2,items:[['植物园项目','施工图','5/18','high'],['烘焙店项目','节点','5/28','mid'],['快闪店项目','收尾','5/10','mid']]},{name:'李四',role:'深化设计',cap:2,items:[['ONIONIO 常州店','深化','5/24','normal'],['空档','可接新项目','5/25','normal']]},{name:'王五',role:'方案设计',cap:2,items:[['植物园项目','方案调整','5/09','high'],['餐饮A 项目','概念','5/21','normal']]},{name:'赵六',role:'方案设计',cap:2,items:[['ONIONIO 常州店','方案配合','5/12','normal']]}];
const more=[['绩效参考导出','只导出参与事实，不计算提成金额','export'],['项目风险处理建议','生成可复制给老板/总监的处理口径','risk'],['AI审图测试台','手机只保留入口，建议电脑端处理','review'],['错题库 / 规则库','电脑端维护，手机端只查看状态','rules'],['导入赫思 Excel','复杂导入放电脑端，避免手机误操作','hess'],['系统自检','检查移动端是否可用','check']];
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));let deliveryFilter='all',peopleFilter='all';
function riskClass(r){return r==='high'?'red':r==='mid'?'gold':'green'}function riskText(r){return r==='high'?'高风险':r==='mid'?'卡点':'正常'}function kindText(k){return k==='contract'?'合同项目':'预排项目'}function daysLeft(d){return Math.ceil((new Date(d)-new Date())/86400000)}function progress(d){return Math.max(12,Math.min(96,100-daysLeft(d)*3))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1600)}
function openSheet(h){$('#sheetContent').innerHTML=h;$('#mask').classList.add('show');$('#sheet').classList.add('show')}function closeSheet(){$('#mask').classList.remove('show');$('#sheet').classList.remove('show')}
function cardProject(p,mode=''){const rc=riskClass(p.risk);return `<article class="card ${rc}" onclick="openProject('${p.id}')"><h3>${p.name}</h3><p>${p.kind==='contract'?'合同交付':'预排结束'}：${p.deliveryLabel} ${p.deliverable}\n预计接铺：${p.access}｜预计开业：${p.opening}\n当前阶段：${p.stage}</p><span class="tag risk">${riskText(p.risk)}</span><span class="tag blue">${kindText(p.kind)}</span><div class="tl"><span>进度</span><span>${p.deliveryLabel}</span></div><div class="track"><div class="fill ${rc}" style="width:${progress(p.delivery)}%"></div></div>${mode==='today'?`<div class="actions"><button class="btn ${p.risk==='high'?'red':'blue'}" onclick="event.stopPropagation();openProject('${p.id}')">打开交付卡</button><button class="btn" onclick="event.stopPropagation();riskAdvice('${p.id}')">处理建议</button></div>`:''}</article>`}
function personCard(p,compact=false){const c=p.items.filter(i=>i[0]!=='空档').length,over=c>p.cap,cls=over?'red':'green';return `<article class="card ${cls}" onclick="openPerson('${p.name}')"><h3>${p.name}｜${p.role}</h3><p>${over?'超过建议上限，新增任务需拆分或换人':'负载正常，可作为备选人选'}\n推荐依据展示为规则化信息，不做黑盒 AI 判断。</p><span class="tag risk">${over?'过载 '+c+'项':'正常 '+c+'项'}</span>${p.items.map(i=>`<div class="line"><b>${i[0]}</b><span>${i[1]}</span><span>${i[2]}</span></div>`).join('')}${compact?`<div class="actions one"><button class="btn" onclick="event.stopPropagation();openPerson('${p.name}')">查看人员负载</button></div>`:''}</article>`}
function renderToday(){const due=projects.filter(p=>daysLeft(p.delivery)<=20).length,pre=projects.filter(p=>p.kind==='pre').length,over=people.filter(x=>x.items.filter(i=>i[0]!=='空档').length>x.cap).length;$('#kpiDue').textContent=due;$('#kpiPre').textContent=pre;$('#kpiOver').textContent=over;$('#todayList').innerHTML=[projects[0],projects[1]].map(p=>cardProject(p,'today')).join('')+personCard(people[0],true)+'<p class="sub" style="margin-top:12px">首页只回答：今天哪些时间和人需要你对齐。</p>'}
function renderDelivery(){const q=($('#projectSearch').value||'').trim().toLowerCase();let a=projects.filter(p=>!q||[p.name,p.stage,p.ownerPlan,p.ownerTech].join(' ').toLowerCase().includes(q));if(deliveryFilter==='contract')a=a.filter(p=>p.kind==='contract');if(deliveryFilter==='pre')a=a.filter(p=>p.kind==='pre');if(deliveryFilter==='risk')a=a.filter(p=>p.risk!=='normal');a.sort((x,y)=>new Date(x.delivery)-new Date(y.delivery));$('#deliveryList').innerHTML=a.length?a.map(p=>cardProject(p)).join(''):'<div class="note">没有匹配项目</div>'}
function renderPeople(){let a=people.slice();if(peopleFilter==='方案')a=a.filter(p=>p.role.includes('方案'));if(peopleFilter==='深化')a=a.filter(p=>p.role.includes('深化'));if(peopleFilter==='over')a=a.filter(p=>p.items.filter(i=>i[0]!=='空档').length>p.cap);$('#peopleList').innerHTML=a.map(p=>personCard(p)).join('')}
function renderMore(){$('#moreList').innerHTML=more.map(m=>`<div class="more-row" onclick="moreAction('${m[2]}')"><div><b>${m[0]}</b><small>${m[1]}</small></div><span>›</span></div>`).join('')+'<div class="note">边界：工时管家负责项目进度、人员负载、工时成本、风险预警；正式绩效、离职结算、接档金额、尾款绩效全部放飞书处理。</div>'}
function openProject(id){const p=projects.find(x=>x.id===id),rc=riskClass(p.risk);openSheet(`<h2>${p.name}</h2><p class="sub">老板问“什么时候结束”，这里一屏回答。</p><div class="big-date"><b>${p.deliveryLabel}</b><span>${p.kind==='contract'?'合同约定':'预排节点'}：${p.deliverable}</span></div><article class="card ${rc}"><h3>当前阶段：${p.stage}</h3><p>${p.issue}\n方案负责人：${p.ownerPlan}｜深化负责人：${p.ownerTech}\n说明：施工阶段只作为进度状态，不作为绩效发放条件。</p></article><div class="actions"><button class="btn blue" onclick="copyBrief('${p.id}')">复制老板口径</button><button class="btn" onclick="riskAdvice('${p.id}')">生成处理建议</button></div>`)}
function openPerson(n){const p=people.find(x=>x.name===n),c=p.items.filter(i=>i[0]!=='空档').length,over=c>p.cap;openSheet(`<h2>${p.name} / ${p.role}</h2><p class="sub">清楚看到他为什么能接或不能再加任务。</p><article class="card ${over?'red':'green'}"><h3>当前 ${c} 个进行中项目</h3><p>${over?'超过建议上限，新增任务需拆分或换人':'负载正常，可以作为备选人选'}\n建议上限：同时 ${p.cap} 个进行中项目。</p></article>${p.items.map(i=>`<article class="card ${riskClass(i[3])}"><h3>${i[0]}</h3><p>阶段：${i[1]}\n交付/释放：${i[2]}</p></article>`).join('')}<div class="actions"><button class="btn" onclick="staffingAdvice('${p.name}')">生成人员安排建议</button><button class="btn blue" onclick="toast('已标记为需拆分任务')">标记拆分</button></div>`)}
function copyBrief(id){const p=projects.find(x=>x.id===id),m=`${p.name}目前${p.kind==='contract'?'合同交付':'预排结束'}节点是${p.deliveryLabel}，内容为${p.deliverable}，预计${p.access}接铺，${p.opening}开业。当前阶段是${p.stage}，${p.issue}。`;navigator.clipboard&&navigator.clipboard.writeText(m);toast('已复制老板口径')}
function riskAdvice(id){const p=projects.find(x=>x.id===id)||projects.find(x=>x.risk!=='normal'),m=`项目：${p.name}\n风险：${p.issue}\n建议：\n1. 今天先确认${p.ownerPlan}与${p.ownerTech}的当前卡点；\n2. 如果${p.deliveryLabel}前无法完成${p.deliverable}，立即拆分任务或调整负责人；\n3. 对外只同步交付影响，不讨论内部绩效或责任分配；\n4. 施工阶段只作为进度状态，不作为绩效发放节点。`;openSheet(`<h2>处理建议</h2><p class="sub">可复制给老板或总监。</p><textarea class="export" id="adviceText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('adviceText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function staffingAdvice(n){const p=people.find(x=>x.name===n),c=p.items.filter(i=>i[0]!=='空档').length,over=c>p.cap,m=`人员：${p.name}｜${p.role}\n当前负载：${c}/${p.cap}\n判断：${over?'不建议新增完整项目，可拆分收尾任务或换人':'可作为备选，但仍需看交付时间冲突'}\n依据：${p.items.map(i=>i[0]+'-'+i[1]+'-'+i[2]).join('；')}\n注意：这是规则化负载判断，不是黑盒 AI 自动派工。`;openSheet(`<h2>人员安排建议</h2><p class="sub">依据角色、负载和项目占用生成。</p><textarea class="export" id="staffText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('staffText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function performanceCSV(){const h=['员工姓名','项目名称','项目角色','参与起始日期','参与结束日期','累计工时','项目总工时','工时占比','当前项目状态','是否接档','接档员工','接档日期','备注'],r=[];people.forEach(p=>p.items.filter(i=>i[0]!=='空档').forEach(i=>{const pr=projects.find(x=>x.name===i[0]);r.push([p.name,i[0],p.role,'—','—','—','—','—',pr?pr.stage:i[1],'—','—','—','仅作绩效参考，不自动计算提成金额'])}));return [h,...r].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n')}
function openExport(){const c=performanceCSV();openSheet(`<h2>绩效参考导出</h2><p class="sub">只导出参与事实，给飞书绩效表作参考；不计算 50% / 40% / 10% 提成。</p><div class="note">工时占比只能作为参考，不能自动等于绩效分配比例。</div><textarea class="export" id="csvText">${c}</textarea><div class="actions"><button class="btn blue" onclick="copyText('csvText')">复制 CSV</button><button class="btn" onclick="downloadCSV()">下载 CSV</button></div>`)}
function copyText(id){const e=document.getElementById(id);e.select();document.execCommand('copy');toast('已复制')}function downloadCSV(){const b=new Blob(['\ufeff'+performanceCSV()],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='绩效参考导出.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已生成 CSV')}
function moreAction(a){if(a==='export')openExport();else if(a==='risk')riskAdvice(projects.find(p=>p.risk!=='normal').id);else if(a==='check')toast('系统自检：移动轻量版正常');else if(a==='review')toast('AI审图已折叠到更多，建议电脑端处理');else toast('该功能保留为电脑端入口，手机端不展开')}
function switchPage(n){$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+n).classList.add('active');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===n));$('#title').textContent={today:'今日',delivery:'交付时间',people:'人员负载',more:'更多'}[n]}
$$('.tab').forEach(t=>t.onclick=()=>switchPage(t.dataset.page));$('#mask').onclick=closeSheet;$('#projectSearch').oninput=renderDelivery;$$('#deliveryFilters .pill').forEach(b=>b.onclick=()=>{$$('#deliveryFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');deliveryFilter=b.dataset.filter;renderDelivery()});$$('#peopleFilters .pill').forEach(b=>b.onclick=()=>{$$('#peopleFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');peopleFilter=b.dataset.role;renderPeople()});function tick(){const d=new Date();$('#clock').textContent=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}tick();setInterval(tick,30000);renderToday();renderDelivery();renderPeople();renderMore();