const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let deliveryFilter='all',peopleFilter='all';
let DATA={projects:[],people:[],tasks:[],loaded:false,message:'正在读取真实项目数据...'};
const SB_URL='https://bgjvuszufqbbialkyeiq.supabase.co';
const SB_KEY='sb_publishable_2yQgdIPmNnxQRTswLSLSwQ_KFaIuUjv';
let sb=null;
function pick(o,ks,d=''){for(const k of ks){if(o&&o[k]!=null&&o[k]!=='')return o[k]}return d}
function txt(v){return v==null?'':String(v)}
function fmtDate(v){if(!v)return '未填';const d=new Date(v);return isNaN(d)?String(v):(d.getMonth()+1)+'月'+d.getDate()+'日'}
function leftDays(v){const d=new Date(v);return isNaN(d)?9999:Math.ceil((d-new Date())/86400000)}
function risk(v,due){const s=txt(v).toLowerCase();if(s.includes('高')||s.includes('risk')||s.includes('red')||s.includes('逾期'))return'high';if(s.includes('中')||s.includes('mid')||s.includes('卡')||s.includes('黄'))return'mid';if(due<=3)return'high';if(due<=10)return'mid';return'normal'}
function riskClass(r){return r==='high'?'red':r==='mid'?'gold':'green'}
function riskText(r){return r==='high'?'高风险':r==='mid'?'卡点':'正常'}
function kindText(k){return k==='pre'?'预排项目':'合同项目'}
function progress(d){const l=leftDays(d);return l===9999?15:Math.max(12,Math.min(96,100-l*3))}
function isManagerPerson(p){const s=(roleOf(p)+' '+nameOf(p)).toLowerCase();return /总监|老板|主管|admin|administrator|manager|owner|director/.test(s)}
function isCompletedProject(o){const s=[o.status,o.stage,o.phase,o.current_stage,o.project_status,o.state,o.close_status,o.name].map(txt).join(' ').toLowerCase();return /已完成|完成|完结|已完结|结束|已结束|结案|已结案|归档|已归档|取消|已取消|作废|关闭|closed|done|completed|cancel/.test(s)}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function openSheet(h){$('#sheetContent').innerHTML=h;$('#mask').classList.add('show');$('#sheet').classList.add('show')}
function closeSheet(){$('#mask').classList.remove('show');$('#sheet').classList.remove('show')}
function empty(m){return `<div class="note">${m}</div>`}
async function allRows(table,select='*',order){let out=[],from=0;while(from<20000){let q=sb.from(table).select(select).range(from,from+999);if(order)q=q.order(order,{ascending:false});const r=await q;if(r.error)throw r.error;out.push(...(r.data||[]));if(!r.data||r.data.length<1000)break;from+=1000}return out}
async function tryRows(table,select='*',order){try{return await allRows(table,select,order)}catch(e){console.warn('load fail',table,e);return[]}}
function nameOf(p){return p?txt(p.name||p.employee_name||p.full_name||p.nickname||p.email):''}
function roleOf(p){return txt((p&&p.role)||(p&&p.job_title)||(p&&p.title)||(p&&p.position)||(p&&p.employee_title)||'未标注')}
function normalProject(o,members,peopleMap){const d=pick(o,['delivery','deliveryDate','delivery_date','deadline','dueDate','contract_delivery_date','completion_date','endDate','finishDate','plannedEnd'],'');const due=leftDays(d);const id=txt(pick(o,['id','project_id','uuid','code'],''));const name=txt(pick(o,['name','title','project_name','projectName','项目名称'],''));const ms=members.filter(m=>String(m.project_id)===String(id||o.project_id));const plan=ms.find(m=>/方案|主案|执行|concept|designer/i.test(txt(m.job_role||m.role)));const tech=ms.find(m=>/深化|施工图|technical|handover/i.test(txt(m.job_role||m.role)));return {id:id||name,name,raw:o,isCompleted:isCompletedProject(o),kind:txt(pick(o,['kind','type','project_type','status_type'],'')).includes('预')?'pre':'contract',delivery:d,deliveryLabel:fmtDate(d),deliverable:txt(pick(o,['deliverable','output','scope','交付物'],'交付节点')),preEnd:fmtDate(pick(o,['preEnd','pre_end','plannedEnd'],d)),access:fmtDate(pick(o,['access','accessDate','site_start','entry_date','预计接铺'],'')),opening:fmtDate(pick(o,['opening','openingDate','open_date','预计开业'],'')),stage:txt(pick(o,['stage','status','phase','current_stage','project_status','当前阶段'],'未填')),risk:risk(pick(o,['risk','riskLevel','risk_level','warning','status'],''),due),ownerPlan:plan?nameOf(peopleMap.get(String(plan.employee_id))):'',ownerTech:tech?nameOf(peopleMap.get(String(tech.employee_id))):'',owner:txt(pick(o,['owner','manager','负责人'],'')),issue:txt(pick(o,['issue','risk_reason','remark','note','备注'],'暂无风险说明'))}}
function normalPerson(o){const n=nameOf(o);return {id:txt(pick(o,['id','user_id','employee_id','uuid'],n)),name:n,role:roleOf(o),cap:getCap(o),items:[],raw:o}}
function getCap(p){const r=roleOf(p);if(/高级深化|深化|施工图|technical/i.test(r))return 4;if(/方案|执行|主案|concept|designer/i.test(r))return 3;return 3}
function memberEmployeeId(m){return txt(pick(m,['employee_id','user_id','member_id','designer_id','assignee_id'],''))}
function memberProjectId(m){return txt(pick(m,['project_id','projectId','project_uuid'],''))}
function memberRole(m){return txt(pick(m,['job_role','role','project_role','member_role','position'],'项目成员'))}
function addProjectItem(person,project,role){if(!person||!project||project.isCompleted)return;if(isManagerPerson(person.raw||person))return;if(person.items.some(i=>String(i.projectId)===String(project.id)))return;person.items.push({projectId:project.id,project:project.name,stage:role||project.stage||'项目参与',date:project.deliveryLabel,risk:project.risk,projectStatus:project.stage})}
function buildData(projectRows,userRows,logRows,memberRows,preplanRows){const peopleMap=new Map();userRows.forEach(u=>peopleMap.set(String(u.id),u));let projects=projectRows.map(p=>normalProject(p,memberRows,peopleMap)).filter(p=>p.name);preplanRows.forEach(pp=>{const n=txt(pp.project_name||pp.name||pp.title);if(n&&!projects.some(p=>p.name===n)){projects.push(normalProject({id:pp.id,name:n,type:'预排',delivery:pp.end_date||pp.planned_end||pp.end,stage:pp.stage||'预排'},[],peopleMap))}});const pMap=new Map(projects.map(p=>[String(p.id),p]));let people=userRows.map(normalPerson).filter(p=>p.name&&!isManagerPerson(p.raw));const personMap=new Map(people.map(p=>[String(p.id),p]));
  memberRows.forEach(m=>{const p=pMap.get(memberProjectId(m));const pe=personMap.get(memberEmployeeId(m));addProjectItem(pe,p,memberRole(m))});
  projects.forEach(p=>{[['ownerPlan','方案负责人'],['ownerTech','深化负责人'],['owner','负责人']].forEach(([field,role])=>{const n=txt(p[field]);if(!n)return;const pe=people.find(x=>x.name===n);addProjectItem(pe,p,role)})});
  people.forEach(p=>p.items.sort((a,b)=>leftDays(a.date)-leftDays(b.date)));
  return {projects,people,tasks:logRows,loaded:true,message:''}}
async function loadRemote(){renderAll();if(!window.supabase){DATA.message='页面没有加载 Supabase SDK';renderAll();return}sb=window.supabase.createClient(SB_URL,SB_KEY,{auth:{storage:window.sessionStorage,persistSession:true,detectSessionInUrl:false}});const u=await sb.auth.getUser();if(!u.data.user){DATA.message='需要先登录，才能读取 Supabase 里的真实项目和人员。';renderAll();showLogin();return}try{let [users,projects,logs,members,preplans]=await Promise.all([tryRows('users','*','is_active'),tryRows('project_cost_summary','*'),tryRows('time_logs','*','log_date'),tryRows('project_members','*'),tryRows('automation_preplans','*')]);if(!projects.length)projects=await tryRows('projects','*');DATA=buildData(projects,users,logs,members,preplans);renderAll();toast(`读取到 ${DATA.projects.length} 个项目、${DATA.people.length} 个可排期人员`)}catch(e){console.error(e);DATA.message='真实数据读取失败，请确认账号权限或刷新重试。';renderAll()}}
function showLogin(){openSheet(`<h2>登录后读取真实数据</h2><p class="sub">轻量版不使用测试数据。请输入工时管家原账号，登录后读取 Supabase 的项目、人员、项目成员与工时记录。</p><input class="search" id="loginEmail" placeholder="邮箱"><input class="search" id="loginPwd" type="password" placeholder="密码"><div class="actions"><button class="btn blue" onclick="doLogin()">登录</button><button class="btn light" onclick="closeSheet()">取消</button></div>`)}
async function doLogin(){const email=$('#loginEmail').value.trim(),password=$('#loginPwd').value;if(!email||!password){toast('请输入邮箱和密码');return}const r=await sb.auth.signInWithPassword({email,password});if(r.error){toast('登录失败：'+r.error.message);return}closeSheet();DATA.message='正在读取真实数据...';await loadRemote()}
function cardProject(p,mode=''){const rc=riskClass(p.risk);return `<article class="card ${rc}" onclick="openProject('${p.id}')"><h3>${p.name}</h3><p>${p.kind==='contract'?'合同交付':'预排结束'}：${p.deliveryLabel} ${p.deliverable}\n预计接铺：${p.access}｜预计开业：${p.opening}\n当前阶段：${p.stage}</p><span class="tag risk">${riskText(p.risk)}</span><span class="tag blue">${kindText(p.kind)}</span>${p.isCompleted?'<span class="tag green">已完结</span>':''}<div class="tl"><span>进度</span><span>${p.deliveryLabel}</span></div><div class="track"><div class="fill ${rc}" style="width:${progress(p.delivery)}%"></div></div>${mode==='today'?`<div class="actions"><button class="btn ${p.risk==='high'?'red':'blue'}" onclick="event.stopPropagation();openProject('${p.id}')">打开交付卡</button><button class="btn" onclick="event.stopPropagation();riskAdvice('${p.id}')">处理建议</button></div>`:''}</article>`}
function personCard(p,compact=false){const c=p.items.length,over=c>p.cap,cls=over?'red':'green';return `<article class="card ${cls}" onclick="openPerson('${p.id||p.name}')"><h3>${p.name}｜${p.role}</h3><p>${over?'超过建议项目上限，新增项目需换人或拆分':'负载正常，可作为备选人选'}\n统计口径：参与且未完结的项目数；主管和总监不纳入。</p><span class="tag risk">${over?'过载 '+c+'个项目':'正常 '+c+'个项目'}</span>${p.items.length?p.items.map(i=>`<div class="line"><b>${i.project}</b><span>${i.stage}</span><span>${i.date}</span></div>`).join(''):'<p style="margin-top:10px">暂无未完结参与项目</p>'}${compact?`<div class="actions one"><button class="btn" onclick="event.stopPropagation();openPerson('${p.id||p.name}')">查看人员负载</button></div>`:''}</article>`}
function renderToday(){const ps=DATA.projects,pe=DATA.people;$('#kpiDue').textContent=ps.filter(p=>!p.isCompleted&&leftDays(p.delivery)<=20).length;$('#kpiPre').textContent=ps.filter(p=>!p.isCompleted&&p.kind==='pre').length;$('#kpiOver').textContent=pe.filter(x=>x.items.length>x.cap).length;let h='';if(ps.length)h+=ps.filter(p=>!p.isCompleted).slice().sort((a,b)=>leftDays(a.delivery)-leftDays(b.delivery)).slice(0,2).map(p=>cardProject(p,'today')).join('');if(pe.length)h+=pe.slice().sort((a,b)=>b.items.length-a.items.length).slice(0,1).map(p=>personCard(p,true)).join('');$('#todayList').innerHTML=h||empty(DATA.message||'没有读取到真实项目或人员数据。')}
function renderDelivery(){const q=($('#projectSearch').value||'').trim().toLowerCase();let a=DATA.projects.filter(p=>!q||[p.name,p.stage,p.ownerPlan,p.ownerTech,p.owner].join(' ').toLowerCase().includes(q));if(deliveryFilter==='contract')a=a.filter(p=>p.kind==='contract');if(deliveryFilter==='pre')a=a.filter(p=>p.kind==='pre');if(deliveryFilter==='risk')a=a.filter(p=>!p.isCompleted&&p.risk!=='normal');a.sort((x,y)=>leftDays(x.delivery)-leftDays(y.delivery));$('#deliveryList').innerHTML=a.length?a.map(p=>cardProject(p)).join(''):empty(DATA.message||'没有匹配项目。')}
function renderPeople(){let a=DATA.people.slice();if(peopleFilter==='方案')a=a.filter(p=>p.role.includes('方案')||p.role.includes('执行'));if(peopleFilter==='深化')a=a.filter(p=>p.role.includes('深化')||p.role.includes('施工图'));if(peopleFilter==='over')a=a.filter(p=>p.items.length>p.cap);$('#peopleList').innerHTML=a.length?a.map(p=>personCard(p)).join(''):empty(DATA.message||'没有读取到可排期人员数据。')}
function renderMore(){$('#moreList').innerHTML=[['刷新真实数据','重新读取 Supabase 项目和人员','refresh'],['绩效参考导出','只导出参与事实，不计算提成金额','export'],['项目风险处理建议','生成可复制给老板/总监的处理口径','risk'],['系统自检','检查移动端是否读取到数据','check']].map(m=>`<div class="more-row" onclick="moreAction('${m[2]}')"><div><b>${m[0]}</b><small>${m[1]}</small></div><span>›</span></div>`).join('')+'<div class="note">人员负载统计口径：参与且未完结的项目数，不按任务条数统计；主管和总监不统计。正式绩效、离职结算、接档金额、尾款绩效全部放飞书处理。</div>'}
function renderAll(){renderToday();renderDelivery();renderPeople();renderMore()}
function openProject(id){const p=DATA.projects.find(x=>x.id==id);if(!p)return;const rc=riskClass(p.risk);openSheet(`<h2>${p.name}</h2><p class="sub">老板问“什么时候结束”，这里一屏回答。</p><div class="big-date"><b>${p.deliveryLabel}</b><span>${p.kind==='contract'?'合同约定':'预排节点'}：${p.deliverable}</span></div><article class="card ${rc}"><h3>当前阶段：${p.stage}</h3><p>${p.issue}\n方案负责人：${p.ownerPlan||p.owner||'未填'}｜深化负责人：${p.ownerTech||'未填'}\n说明：施工阶段只作为进度状态，不作为绩效发放条件。</p></article><div class="actions"><button class="btn blue" onclick="copyBrief('${p.id}')">复制老板口径</button><button class="btn" onclick="riskAdvice('${p.id}')">生成处理建议</button></div>`)}
function openPerson(id){const p=DATA.people.find(x=>x.id==id||x.name==id);if(!p)return;const c=p.items.length,over=c>p.cap;openSheet(`<h2>${p.name} / ${p.role}</h2><p class="sub">统计口径：参与且未完结的项目数，不按任务条数；主管和总监不纳入。</p><article class="card ${over?'red':'green'}"><h3>当前 ${c} 个未完结参与项目</h3><p>${over?'超过建议上限，新增项目需拆分或换人':'负载正常，可以作为备选人选'}\n建议上限：同时 ${p.cap} 个未完结项目。</p></article>${p.items.length?p.items.map(i=>`<article class="card ${riskClass(i.risk)}"><h3>${i.project}</h3><p>项目角色：${i.stage}\n交付/释放：${i.date}\n项目状态：${i.projectStatus||'未填'}</p></article>`).join(''):empty('暂无未完结参与项目')}<div class="actions"><button class="btn" onclick="staffingAdvice('${p.id||p.name}')">生成人员安排建议</button><button class="btn blue" onclick="toast('已标记为需拆分任务')">标记拆分</button></div>`)}
function copyBrief(id){const p=DATA.projects.find(x=>x.id==id);if(!p)return;const m=`${p.name}目前${p.kind==='contract'?'合同交付':'预排结束'}节点是${p.deliveryLabel}，内容为${p.deliverable}，预计${p.access}接铺，${p.opening}开业。当前阶段是${p.stage}，${p.issue}。`;navigator.clipboard&&navigator.clipboard.writeText(m);toast('已复制老板口径')}
function riskAdvice(id){const p=DATA.projects.find(x=>x.id==id)||DATA.projects.find(x=>!x.isCompleted&&x.risk!=='normal');if(!p){toast('暂无项目数据');return}const m=`项目：${p.name}\n风险：${p.issue}\n建议：\n1. 今天先确认${p.ownerPlan||p.owner||'负责人'}与${p.ownerTech||'深化负责人'}的当前卡点；\n2. 如果${p.deliveryLabel}前无法完成${p.deliverable}，立即拆分项目工作或调整负责人；\n3. 对外只同步交付影响，不讨论内部绩效或责任分配；\n4. 人员负载按未完结参与项目统计，不按任务条数统计。`;openSheet(`<h2>处理建议</h2><p class="sub">可复制给老板或总监。</p><textarea class="export" id="adviceText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('adviceText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function staffingAdvice(id){const p=DATA.people.find(x=>x.id==id||x.name==id);if(!p)return;const m=`人员：${p.name}｜${p.role}\n当前负载：${p.items.length}/${p.cap} 个未完结参与项目\n依据：${p.items.map(i=>i.project+'-'+i.stage+'-'+i.date).join('；')||'暂无未完结参与项目'}\n注意：这是按项目数统计的规则化负载判断，不是按任务条数统计，也不是黑盒 AI 自动派工。`;openSheet(`<h2>人员安排建议</h2><textarea class="export" id="staffText">${m}</textarea><div class="actions"><button class="btn blue" onclick="copyText('staffText')">复制建议</button><button class="btn light" onclick="closeSheet()">关闭</button></div>`)}
function performanceCSV(){const h=['员工姓名','项目名称','项目角色','参与起始日期','参与结束日期','累计工时','项目总工时','工时占比','当前项目状态','是否接档','接档员工','接档日期','备注'],r=[];DATA.people.forEach(p=>p.items.forEach(i=>r.push([p.name,i.project,p.role,'','','','','',i.projectStatus,'','','','仅作绩效参考，不自动计算提成金额'])));return [h,...r].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n')}
function openExport(){const c=performanceCSV();openSheet(`<h2>绩效参考导出</h2><p class="sub">只导出参与事实，给飞书绩效表作参考；不计算 50% / 40% / 10% 提成。</p><div class="note">工时占比只能作为参考，不能自动等于绩效分配比例。</div><textarea class="export" id="csvText">${c}</textarea><div class="actions"><button class="btn blue" onclick="copyText('csvText')">复制 CSV</button><button class="btn" onclick="downloadCSV()">下载 CSV</button></div>`)}
function copyText(id){const e=document.getElementById(id);e.select();document.execCommand('copy');toast('已复制')}
function downloadCSV(){const b=new Blob(['\ufeff'+performanceCSV()],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='绩效参考导出.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('已生成 CSV')}
function moreAction(a){if(a==='refresh')loadRemote();else if(a==='export')openExport();else if(a==='risk'){const p=DATA.projects.find(x=>!x.isCompleted&&x.risk!=='normal');riskAdvice(p&&p.id)}else if(a==='check')toast(`读取到 ${DATA.projects.length} 个项目、${DATA.people.length} 个可排期人员`)}
function switchPage(n){$$('.page').forEach(p=>p.classList.remove('active'));$('#page-'+n).classList.add('active');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===n));$('#title').textContent={today:'今日',delivery:'交付时间',people:'人员负载',more:'更多'}[n]}
$$('.tab').forEach(t=>t.onclick=()=>switchPage(t.dataset.page));$('#mask').onclick=closeSheet;$('#projectSearch').oninput=renderDelivery;$$('#deliveryFilters .pill').forEach(b=>b.onclick=()=>{$$('#deliveryFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');deliveryFilter=b.dataset.filter;renderDelivery()});$$('#peopleFilters .pill').forEach(b=>b.onclick=()=>{$$('#peopleFilters .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');peopleFilter=b.dataset.role;renderPeople()});function tick(){const d=new Date();$('#clock').textContent=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}tick();setInterval(tick,30000);renderAll();loadRemote();