function workloadIsDeparted(p){if(!p)return false;var active=p.is_active??p.active??p.enabled??p.isActive??p.available??p.can_schedule;if(active===false||active===0||active==='false'||active==='0'||active==='否'||active==='no')return true;var date=p.left_at||p.departure_date||p.resigned_at||p.quit_date||p.leave_date||p.termination_date||p['离职日期'];if(date)return true;var s=[p.status,p.employee_status,p.employment_status,p.state,p.user_status,p.remark,p.note,p.role,p.position].map(x=>x==null?'':String(x)).join(' ').toLowerCase();return /离职|已离职|离任|停用|禁用|不在职|非在职|inactive|resigned|departed|left|disabled|terminated/.test(s)}
function workloadActivePerson(p){return p&&p.name&&!p.departed&&!workloadIsDeparted(p.raw||p)&&!isManagerPerson(p.raw||p)}
function workloadTextOfProject(p){var r=(p&&p.raw)||p||{};return [p&&p.stage,p&&p.status,p&&p.projectStatus,p&&p.project_status,p&&p.state,r.status,r.stage,r.phase,r.current_stage,r.project_status,r.state,r.close_status,r.name,p&&p.name].map(x=>x==null?'':String(x)).join(' ')}
function workloadIsExplicitOngoingProject(p){return /未完成|未完工|未完结|未结束|进行中|进行状态|方案阶段|施工图阶段|施工阶段|施工中|深化中/.test(workloadTextOfProject(p))}
function workloadProjectCounts(p){if(!p)return false;if(workloadIsExplicitOngoingProject(p))return true;var s=workloadTextOfProject(p);if(/已完成|已完工|已结束|已结案|已归档|已暂停|完成|完结|结束|结案|归档|暂停|停滞|取消|作废|关闭|closed|done|completed|cancel/.test(s))return false;return !p.isCompleted}
const __oldIsCompletedProject=typeof isCompletedProject==='function'?isCompletedProject:function(){return false};
isCompletedProject=function(o){if(workloadIsExplicitOngoingProject(o))return false;return __oldIsCompletedProject(o)};
const __oldNormalPerson=normalPerson;normalPerson=function(o){var p=__oldNormalPerson(o);p.departed=workloadIsDeparted(o);return p};
const __oldAddProjectItem=addProjectItem;addProjectItem=function(person,project,role){if(!workloadActivePerson(person))return;if(!workloadProjectCounts(project))return;if(workloadIsExplicitOngoingProject(project))project.isCompleted=false;return __oldAddProjectItem(person,project,role)};
const __oldBuildData=buildData;buildData=function(projectRows,userRows,logRows,memberRows,preplanRows){var d=__oldBuildData(projectRows,userRows,logRows,memberRows,preplanRows);d.people=(d.people||[]).filter(workloadActivePerson);return d};
const __oldRenderMore=renderMore;renderMore=function(){__oldRenderMore();var box=document.querySelector('#moreList .note');if(box)box.textContent='人员负载统计口径：在职人员参与且未完成/未完工/进行中的项目计入负载；已完工、暂停、取消、归档项目不计入；离职人员、主管和总监不统计。正式绩效、离职结算、接档金额、尾款绩效全部放飞书处理。'};
